### ISSUE TITLE
Can't add games to game list

### ISSUE THREAD

**Issue by Sunderland93** [flathub/net.rpcs3.RPCS3#776] opened 2022-01-17 09:37 UTC
Hello. My game folder is /home/sunderland93/Downloads/PS3. When I choose "Add game" option and select this folder, the "Open" button is not work. Official Appimage works fine.

**Comment by Lctrs** [comment] 2022-01-17 14:37
Hi. Can you attach rpcs3's log ? You can find it under `~/.var/app/net.rpcs3.RPCS3`.

**Comment by Sunderland93** [comment] 2022-01-17 14:42
[RPCS3.log](https://github.com/flathub/net.rpcs3.RPCS3/files/7882609/RPCS3.log)

**Comment by Lctrs** [comment] 2022-01-17 14:44
Have you reproduced your issue before closing rpcs3 and submitting the log file ?

**Comment by Sunderland93** [comment] 2022-01-17 14:47
>Have you reproduced your issue before closing rpcs3 and submitting the log file ?

Yes

**Comment by Lctrs** [comment] 2022-01-17 15:03
It doesn't seem there is anything related to this in the log. Do you have an `.log.gz` file as well in the same folder ?

Also, does running `flatpak run --filesystem=home:rw net.rpcs3.RPCS3` in the terminal help ?

**Comment by Lctrs** [comment] 2022-01-17 15:04
It doesn't seem there is anything related to this in the log. Do you have an `.log.gz` file as well in the same folder ?

Also, does running `flatpak run --filesystem=home:rw net.rpcs3.RPCS3` in the terminal help ?

**Comment by Sunderland93** [comment] 2022-01-17 15:11
>Do you have an .log.gz file as well in the same folder ?

Yes but it's empty

>Also, does running flatpak run --filesystem=home:rw net.rpcs3.RPCS3 in the terminal help ?

No, and output gives an error: 
```
Debugger: 0
Failed to set RLIMIT_MEMLOCK size to 2 GiB. Try to update your system configuration.
[ALSOFT] (EE) Failed to set real-time priority for thread: Операция не позволена (1)
sh: строка 1: xdg-mime: command not found
```

**Comment by Sunderland93** [comment] 2022-01-19 19:24
I think the problem is related to this : https://github.com/flatpak/xdg-desktop-portal/issues/594 https://github.com/flatpak/xdg-desktop-portal/issues/591

**Comment by lhindir** [comment] 2022-03-30 00:33
I also have this issue, but I don't think either of the above issues are related. No locations are mounted with `:create`, and `--persist` is for directories within the sandbox, not external game directories.

Nothing is logged in RPCS3 (at least, nothing that shows up in the GUI's log) when I try to add games via this method. After choosing "Open", the file picker closes and the game list refreshes, but the game isn't added.

Strangely, for the same game, choosing the folder via "Boot Game" launches it just fine. So it does seem like a missing permission causing "Add Game" to fail. Maybe "Add Game" writes something to a nonstandard directory in the sandbox (i.e. not `data`, `cache`, or `config`), and a `--persist` option is needed?

**Comment by Lctrs** [comment] 2022-03-30 08:18
By default, we mount your $HOME as a read only filesystem.

If your games directory is in your $HOME, you can try to make it writable by using `--filesystem=home`. If not, it would be `--filesystem=/path/to/your/games/dir`.

**Closed** 2022-06-12 15:33 UTC

**Comment by lhindir** [comment] 2022-06-19 16:11
In my case, that wasn’t the issue: since “Boot Game” worked on the same files, the app had access. I think the actual issue was that I thought “Add Game” worked on anything, but it only works on disc dumps, not PSN dumps. For PSN dumps you need “Install packages/edats/raps”.
