### ISSUE TITLE
game .desktop does not work

### ISSUE THREAD

**Issue by B-Nerd** [flathub/net.rpcs3.RPCS3#1746] opened 2024-08-29 20:40 UTC
when i create a .desktop it does not work that is because where the is in the .desktop file is wrong it is not here Exec="/app/bin/rpcs3" but here Exec="/var/lib/flatpak/exports/bin/net.rpcs3.RPCS3

**Comment by j8r** [comment] 2024-08-29 22:49
Duplicate of https://github.com/flathub/net.rpcs3.RPCS3/issues/1449 ? If yes, can be closed to centralize the issue.

**Comment by B-Nerd** [comment] 2024-08-30 07:10
> Duplicate of #1449 ? If yes, can be closed to centralize the issue.

yep misread that one

**Closed** 2024-08-30 07:11 UTC
